// Generated Firebase configuration
// This file is generated by FlutterFire CLI
// DO NOT EDIT - Update via: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe7yurxlHy3RNDU13w73xLHSl8eROT7uU',
    appId: '1:1421545920:android:5c31379755272fa5727825',
    messagingSenderId: '1421545920',
    projectId: 'reliq-faith-app',
    databaseURL: 'https://reliq-faith-app.firebaseio.com',
    storageBucket: 'reliq-faith-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpYhjul0JfujphgUO520jecRsdKxb1l3c',
    appId: '1:1421545920:ios:abb97f1fbf6f4617727825',
    messagingSenderId: '1421545920',
    projectId: 'reliq-faith-app',
    databaseURL: 'https://reliq-faith-app.firebaseio.com',
    storageBucket: 'reliq-faith-app.firebasestorage.app',
    iosBundleId: 'com.reliq.app',
  );
}
