// ─────────────────────────────────────────────────────────────────────────────
// CHAT REPOSITORY — lib/repositories/chat_repository.dart
// ─────────────────────────────────────────────────────────────────────────────
//
// WHAT THIS FILE DOES:
//   Handles all real-time messaging between users using Firestore streams.
//   Supports direct (1-to-1) chats only for MVP.
//   Group chats can be added later by extending the participants array.
//
// FIRESTORE STRUCTURE:
//   /chats/{chatId}
//     - id, participants (array of 2 userIds), participant_names (map),
//       last_message, updated_at
//     /messages/{messageId}
//       - id, chat_id, sender_id, text, created_at
//
// HOW CHAT IDs WORK:
//   Direct chat IDs are generated by sorting both user IDs alphabetically
//   and joining them with an underscore: "uid1_uid2"
//   This means the same two users always get the same chat document —
//   no duplicates, no lookup needed.
//   Example: user "abc" and user "xyz" → chatId = "abc_xyz"
//
// REAL-TIME:
//   Both watchChats() and watchMessages() return Streams that stay open.
//   New messages appear instantly without any polling or manual refresh.
//   This is Firestore's core strength for chat features.
//
// FIRESTORE RULES REQUIRED:
//   - /chats: read if request.auth.uid in participants
//   - /chats/{id}/messages: read if user is a participant of the chat
//   - /chats/{id}/messages: create if sender_id matches auth uid
// ─────────────────────────────────────────────────────────────────────────────

import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/chat.dart';
import '../utils/firestore_utils.dart';

class ChatRepository {
  final FirebaseFirestore _db;

  ChatRepository({FirebaseFirestore? db})
      : _db = db ?? FirebaseFirestore.instance;

  // Generates a deterministic chat ID for two users.
  // Sorting ensures "abc_xyz" and "xyz_abc" always resolve to the same ID
  // regardless of which user initiates the conversation.
  String directChatId(String firstUserId, String secondUserId) {
    final ids = [firstUserId, secondUserId]..sort();
    return '${ids[0]}_${ids[1]}';
  }

  // Streams all chat threads the user is a participant in.
  // Uses arrayContains to filter only chats where the user's ID
  // is in the participants array — users can't see other people's chats.
  // Sorted by most recently updated so newest conversations appear first.
  Stream<List<ChatThread>> watchChats(String userId) {
    return _db
        .collection('chats')
        .where('participants', arrayContains: userId)
        .snapshots()
        .map((snap) {
          final chats = snap.docs.map((doc) {
            return ChatThread.fromJson(withDocId(doc));
          }).toList();
          // Sort client-side by updatedAt since Firestore doesn't allow
          // orderBy with arrayContains without a composite index
          chats.sort((a, b) => b.updatedAt.compareTo(a.updatedAt));
          return chats;
        });
  }

  // Streams messages for a specific chat in chronological order.
  // Limited to last 100 messages — add pagination later for long conversations.
  // Messages are ordered ascending (oldest first) so they display
  // naturally in a chat bubble list.
  Stream<List<ChatMessage>> watchMessages(String chatId) {
    return _db
        .collection('chats')
        .doc(chatId)
        .collection('messages')
        .orderBy('created_at')
        .limit(100)
        .snapshots()
        .map((snap) => snap.docs.map((doc) {
              return ChatMessage.fromJson(withDocId(doc));
            }).toList());
  }

  // Sends a message and updates the chat thread in one atomic batch.
  // Two writes happen together:
  //   1. The chat document is created or updated (merge: true means it won't
  //      overwrite existing fields — only updates what's provided)
  //   2. A new message document is added to the messages subcollection
  //
  // Using a batch ensures both writes succeed or both fail —
  // prevents a message being sent without the chat thread being updated,
  // which would cause the conversation list to show stale data.
  //
  // Empty messages are silently ignored before hitting Firestore.
  Future<void> sendMessage({
    required String chatId,
    required String senderId,
    required List<String> participants,
    required Map<String, String> participantNames,
    required String text,
  }) async {
    final trimmed = text.trim();
    if (trimmed.isEmpty) return;

    final chatRef = _db.collection('chats').doc(chatId);
    final messageRef = chatRef.collection('messages').doc();

    final batch = _db.batch();

    // Update the chat thread with the latest message preview and timestamp.
    // SetOptions(merge: true) creates the document if it doesn't exist yet,
    // or merges these fields into it if it does — safe for first message.
    batch.set(
      chatRef,
      {
        'id': chatId,
        'participants': participants,
        'participant_names': participantNames,
        'last_message': trimmed,
        'updated_at': FieldValue.serverTimestamp(),
      },
      SetOptions(merge: true),
    );

    // Add the actual message to the subcollection
    batch.set(messageRef, {
      'id': messageRef.id,
      'chat_id': chatId,
      'sender_id': senderId,
      'text': trimmed,
      'created_at': FieldValue.serverTimestamp(),
    });

    await batch.commit();
  }
}
