// ─────────────────────────────────────────────────────────────────────────────
// CHAT MODELS — lib/models/chat.dart
// ─────────────────────────────────────────────────────────────────────────────
//
// WHAT THIS FILE DOES:
//   Defines the two data models used for the chat feature:
//   - ChatThread: represents a conversation between two users
//   - ChatMessage: represents a single message inside a conversation
//
// FIRESTORE MAPPING:
//   ChatThread  → /chats/{chatId}
//   ChatMessage → /chats/{chatId}/messages/{messageId}
//
// HOW CHAT IDs WORK:
//   Chat IDs are generated by sorting both user IDs and joining with "_".
//   This means the same two users always share the same chat document.
//   See ChatRepository.directChatId() for the generation logic.
// ─────────────────────────────────────────────────────────────────────────────

import '../utils/firestore_utils.dart';

// Represents a conversation thread between two (or more) users.
// Stored at /chats/{chatId} in Firestore.
class ChatThread {
  final String id;

  // List of user IDs in this conversation.
  // For direct chats this always has exactly 2 entries.
  final List<String> participants;

  // Map of userId → display name for each participant.
  // Stored on the chat document so we don't need to fetch user profiles
  // just to show a name in the chat list — avoids extra Firestore reads.
  // Example: { "uid1": "Sarah M.", "uid2": "David K." }
  final Map<String, String> participantNames;

  // Preview of the last message — shown in the chat list screen.
  // Updated every time a new message is sent via ChatRepository.sendMessage().
  final String lastMessage;

  // When the last message was sent — used to sort conversations newest first.
  final DateTime updatedAt;

  ChatThread({
    required this.id,
    required this.participants,
    this.participantNames = const {},
    this.lastMessage = '',
    required this.updatedAt,
  });

  factory ChatThread.fromJson(Map<String, dynamic> json) {
    // participant_names is stored as a Map in Firestore.
    // Cast safely — Firestore maps come back as Map<dynamic, dynamic>
    // so we convert all keys and values to String explicitly.
    final rawNames = json['participant_names'] as Map? ?? {};
    return ChatThread(
      id: json['id'] ?? '',
      participants: json['participants'] != null
          ? List<String>.from(json['participants'])
          : [],
      participantNames: rawNames.map(
        (key, value) => MapEntry(key.toString(), value.toString()),
      ),
      lastMessage: json['last_message'] ?? '',
      updatedAt: readFirestoreDate(json['updated_at']),
    );
  }

  // Returns the display name of the OTHER person in the conversation.
  // Used in the chat list to show who you're talking to.
  // Falls back to 'Reliq user' if the name isn't in the map yet
  // (can happen briefly while the chat document is being created).
  String otherName(String currentUserId) {
    final otherId = participants.firstWhere(
      (id) => id != currentUserId,
      orElse: () => currentUserId, // fallback to self if something goes wrong
    );
    return participantNames[otherId] ?? 'Reliq user';
  }
}

// Represents a single message inside a chat conversation.
// Stored at /chats/{chatId}/messages/{messageId} in Firestore.
class ChatMessage {
  final String id;

  // The chat this message belongs to — matches the parent document ID.
  final String chatId;

  // The Firebase Auth UID of the user who sent this message.
  // Used to determine which side of the chat bubble to show it on.
  final String senderId;

  final String text;
  final DateTime createdAt;

  ChatMessage({
    required this.id,
    required this.chatId,
    required this.senderId,
    required this.text,
    required this.createdAt,
  });

  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    return ChatMessage(
      id: json['id'] ?? '',
      chatId: json['chat_id'] ?? '',
      senderId: json['sender_id'] ?? '',
      text: json['text'] ?? '',
      createdAt: readFirestoreDate(json['created_at']),
    );
  }
}
